apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: edge-service
build:
  artifacts:
  - image: ernestoacostacuba/edge-service
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base
      env:
        - BP_JVM_VERSION=11.*
  tagPolicy:
    gitCommit: {
                 variant: AbbrevTreeSha,
                 ignoreChanges: true
    }

  local:
    push: false

deploy:
  kubectl:
    manifests:
    - k8s/*.yml
