apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: edge-service
# Enforce SKaffold to use Jib
build:
  local:
    push: false
  # Generated artifact
  artifacts:
    - image: ernestoacostacuba/edge-service
      context: .
      jib:
        type: maven
        args: [-Pjib, -DskipTests=true, -Dspring.profiles.active=mysqldev]
# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - k8s/*.yml
